const admin = require("firebase-admin/app");
admin.initializeApp();

const checkCloudPayments = require("./check_cloud_payments.js");
exports.checkCloudPayments = checkCloudPayments.checkCloudPayments;
const createNotificationsForUsers = require("./create_notifications_for_users.js");
exports.createNotificationsForUsers =
  createNotificationsForUsers.createNotificationsForUsers;
const restorePurchase = require("./restore_purchase.js");
exports.restorePurchase = restorePurchase.restorePurchase;
const setDefaultHideOnCreate = require("./set_default_hide_on_create.js");
exports.setDefaultHideOnCreate = setDefaultHideOnCreate.setDefaultHideOnCreate;
const getCourseWebhook = require("./get_course_webhook.js");
exports.getCourseWebhook = getCourseWebhook.getCourseWebhook;
const pushNoLogin = require("./push_no_login.js");
exports.pushNoLogin = pushNoLogin.pushNoLogin;
const pushNoAudio = require("./push_no_audio.js");
exports.pushNoAudio = pushNoAudio.pushNoAudio;
const pushNoChat = require("./push_no_chat.js");
exports.pushNoChat = pushNoChat.pushNoChat;
const pushMenstruationDay = require("./push_menstruation_day.js");
exports.pushMenstruationDay = pushMenstruationDay.pushMenstruationDay;
const chatMessageStream = require("./chat_message_stream.js");
exports.chatMessageStream = chatMessageStream.chatMessageStream;
const createCalendarForUser = require("./create_calendar_for_user.js");
exports.createCalendarForUser = createCalendarForUser.createCalendarForUser;
const setNewsHideDefault = require("./set_news_hide_default.js");
exports.setNewsHideDefault = setNewsHideDefault.setNewsHideDefault;
const setVideosHideDefault = require("./set_videos_hide_default.js");
exports.setVideosHideDefault = setVideosHideDefault.setVideosHideDefault;
